Repository apache/lucenenet, pull requests merged in 2022-10, with the labels that each got.

#656 fix: Fixed Infinite loop in HttpClientBase
  src/Lucene.Net.Replicator/Http/HttpClientBase.cs
Labels: hacktoberfest-accepted

#654 fix: Aligned FrenchStemmer.cs with Java code
  src/Lucene.Net.Analysis.Common/Analysis/Fr/FrenchStemmer.cs
Labels: hacktoberfest-accepted

#685 .editorconfig: Added suppression for CA2249: Consider using String.Contains instead of String.IndexOf
  .editorconfig
Labels: hacktoberfest-accepted

#687 Lucene.Net.Tests.Analysis.SmartCn.TestHMMChineseTokenizerFactory::TestHHMMSegmenter() Added LuceneNetSpecificAttribute
  src/Lucene.Net.Tests.Analysis.SmartCn/TestHMMChineseTokenizerFactory.cs
Labels: hacktoberfest-accepted

#688 Lucene.Net.Analysis.Cn.Smart.Utility: Changed SPACES to use an encoded character for '\u3000' so it is visible in the designer.
  src/Lucene.Net.Analysis.SmartCn/Utility.cs
Labels: is:enhancement, hacktoberfest-accepted

#689 fix: Fixed '&' to '&&' in DutchStemmer
  src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchStemmer.cs
Labels: is:bug, hacktoberfest-accepted

#686 SWEEP: Fixed ArgumentOutOfRange parameters so the message is passed into the 2nd parameter.
  src/Lucene.Net.Analysis.Common/Analysis/Util/BufferedCharFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/OpenStringBuilder.cs
  src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/MultiTrie2.cs
  src/Lucene.Net.Benchmark/ByTask/Feeds/RandomFacetSource.cs
  src/Lucene.Net.Facet/Taxonomy/LRUHashMap.cs
  src/Lucene.Net.Grouping/AbstractFirstPassGroupingCollector.cs
  src/Lucene.Net.Spatial/Prefix/Tree/Cell.cs
  src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs
  src/Lucene.Net/Analysis/TokenAttributes/CharTermAttribute.cs
  src/Lucene.Net/Index/ConcurrentMergeScheduler.cs
  src/Lucene.Net/Search/BooleanClause.cs
  src/Lucene.Net/Search/SearcherLifetimeManager.cs
  src/Lucene.Net/Store/BufferedIndexInput.cs
  src/Lucene.Net/Store/BufferedIndexOutput.cs
  src/Lucene.Net/Store/ByteBufferIndexInput.cs
  src/Lucene.Net/Store/DataInput.cs
  src/Lucene.Net/Store/Lock.cs
  src/Lucene.Net/Store/LockStressTest.cs
  src/Lucene.Net/Util/CharsRef.cs
Labels: is:bug, hacktoberfest-accepted

#691 SWEEP: Prefer 'AsSpan' over 'Substring' when span-based overloads are available
  Directory.Build.targets
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs
  src/Lucene.Net.Analysis.Common/Analysis/Pattern/PatternReplaceCharFilter.cs
  src/Lucene.Net.Analysis.Phonetic/Language/DoubleMetaphone.cs
  src/Lucene.Net.Benchmark/ByTask/Feeds/EnwikiContentSource.cs
  src/Lucene.Net.Benchmark/ByTask/Tasks/SearchTravRetHighlightTask.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/EscapeQuerySyntaxImpl.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs
  src/Lucene.Net.Replicator/Http/HttpClientBase.cs
  src/Lucene.Net.Suggest/Suggest/Analyzing/AnalyzingInfixSuggester.cs
  src/Lucene.Net/Util/AttributeSource.cs
Labels: is:enhancement, hacktoberfest-accepted

#692 SWEEP: Lucene.Net.Benchmark.Support.TagSoup: Review
  src/Lucene.Net.Benchmark/Support/TagSoup/Guard.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/HTMLScanner.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/PYXScanner.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/PYXWriter.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/Parser.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/ScanHandler.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/Scanner.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/Schema.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/XMLWriter.cs
Labels: hacktoberfest-accepted

#696 SWEEP: Add a nested comment explaining why this method is empty.
  src/Lucene.Net.Benchmark/ByTask/Tasks/ReadTokensTask.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/PYXScanner.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/PYXWriter.cs
  src/Lucene.Net.Facet/Taxonomy/Directory/DirectoryTaxonomyWriter.cs
  src/Lucene.Net.Facet/Taxonomy/WriterCache/CollisionMap.cs
  src/Lucene.Net.Queries/Function/FunctionQuery.cs
  src/Lucene.Net.QueryParser/Classic/QueryParser.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs
  src/Lucene.Net.QueryParser/Surround/Parser/QueryParser.cs
  src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs
  src/Lucene.Net/Analysis/Tokenizer.cs
  src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs
  src/Lucene.Net/Index/DocumentsWriterFlushControl.cs
  src/Lucene.Net/Index/FrozenBufferedUpdates.cs
  src/Lucene.Net/Index/NoMergePolicy.cs
  src/Lucene.Net/Index/ParallelCompositeReader.cs
  src/Lucene.Net/Search/IndexSearcher.cs
  src/Lucene.Net/Search/MatchAllDocsQuery.cs
  src/Lucene.Net/Support/Index/TaskMergeScheduler.cs
  src/Lucene.Net/Util/AttributeSource.cs
  src/Lucene.Net/Util/Automaton/State.cs
  src/Lucene.Net/Util/InfoStream.cs
  src/Lucene.Net/Util/MergedIterator.cs
  src/Lucene.Net/Util/RamUsageEstimator.cs
Labels: hacktoberfest-accepted

#697 PERFORMANCE: Lucene.Net.Util.MergedEnumerator: Changed to use J2N.Collections.Generic.Comparer<T> to match Java behaviors and for better performance
  src/Lucene.Net/Util/MergedIterator.cs
Labels: hacktoberfest-accepted

#698 SWEEP: Renamed classes from using Iterable and Iterator to Enumerable and Enumerator, where appropropriate
  src/Lucene.Net.Codecs/Memory/MemoryDocValuesConsumer.cs
  src/Lucene.Net.Highlighter/VectorHighlight/BaseFragListBuilder.cs
  src/Lucene.Net.TestFramework/Codecs/Lucene42/Lucene42DocValuesConsumer.cs
  src/Lucene.Net.TestFramework/Codecs/MissingOrdRemapper.cs
  src/Lucene.Net.TestFramework/Index/RandomIndexWriter.cs
  src/Lucene.Net.Tests/Index/TestIndexWriter.cs
  src/Lucene.Net.Tests/Index/TestIndexableField.cs
  src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs
  src/Lucene.Net/Index/BufferedUpdatesStream.cs
  src/Lucene.Net/Index/CoalescedUpdates.cs
  src/Lucene.Net/Index/FrozenBufferedUpdates.cs
  src/Lucene.Net/Util/AttributeSource.cs
  src/Lucene.Net/Util/RamUsageEstimator.cs
  src/Lucene.Net/Util/WeakIdentityMap.cs
Labels: hacktoberfest-accepted

#703 BREAKING: Lucene.Net.Analysis.Cjk.CJKBigramFilter: Changed the value of CJKScript.ALL
  src/Lucene.Net.Analysis.Common/Analysis/Cjk/CJKBigramFilter.cs
Labels: hacktoberfest-accepted

#702 SWEEP: Marked all singleton "Holder" classes static. Fixes #659.
  src/Lucene.Net.Analysis.Common/Analysis/Ar/ArabicAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Bg/BulgarianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ca/CatalanAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Cjk/CJKAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ckb/SoraniAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Cz/CzechAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Da/DanishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/De/GermanAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/El/GreekAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/En/EnglishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Es/SpanishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Eu/BasqueAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fa/PersianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fi/FinnishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fr/FrenchAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ga/IrishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Gl/GalicianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hi/HindiAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hu/HungarianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hy/ArmenianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Id/IndonesianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/It/ItalianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Lv/LatvianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/No/NorwegianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Pt/PortugueseAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ro/RomanianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ru/RussianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Sv/SwedishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Tr/TurkishAnalyzer.cs
  src/Lucene.Net.Analysis.Kuromoji/Dict/CharacterDefinition.cs
  src/Lucene.Net.Analysis.Kuromoji/Dict/ConnectionCosts.cs
  src/Lucene.Net.Analysis.Kuromoji/Dict/TokenInfoDictionary.cs
  src/Lucene.Net.Analysis.Kuromoji/Dict/UnknownDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/SmartChineseAnalyzer.cs
  src/Lucene.Net.Analysis.Stempel/Pl/PolishAnalyzer.cs
  src/Lucene.Net/Search/TimeLimitingCollector.cs
Labels: hacktoberfest-accepted

#705 Fix: Remove the ToString call in order to use a strongly-typed StringBuilder overload
  src/Lucene.Net.Analysis.Common/Analysis/Compound/Hyphenation/PatternParser.cs
  src/Lucene.Net.Tests/Analysis/TestToken.cs
  src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs
  src/Lucene.Net.Tests/Search/TestCustomSearcherSort.cs
Labels: hacktoberfest-accepted

#706 BUG: Lucene.Net.Tests.Index.TestIndexWriter: Finished port of RandomFailingFieldEnumerable.
  src/Lucene.Net.Tests/Index/TestIndexWriter.cs
Labels: hacktoberfest-accepted

#707 Fix for net461 dependency conflict after upgrading Newtonsoft.Json.
  .build/TestReferences.Common.targets
  .build/dependencies.props
  src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj
  src/Lucene.Net.Tests.Analysis.SmartCn/Lucene.Net.Tests.Analysis.SmartCn.csproj
  src/Lucene.Net.Tests.Benchmark/Lucene.Net.Tests.Benchmark.csproj
Labels: hacktoberfest-accepted

#693 chore: Added suppression attributes to CA1822
  src/Lucene.Net.Analysis.Phonetic/Language/MatchRatingApproachEncoder.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneTestFrameworkInitializer.cs
  src/Lucene.Net/Search/FieldCacheImpl.cs
  src/Lucene.Net/Search/Similarities/BasicModelBE.cs
Labels: hacktoberfest-accepted

#710 Fixed immutable collection issues
  src/Lucene.Net.Analysis.Common/Analysis/Ar/ArabicAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Bg/BulgarianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ca/CatalanAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Cjk/CJKAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ckb/SoraniAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Core/StopAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Cz/CzechAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Da/DanishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/De/GermanAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/El/GreekAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/En/EnglishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Es/SpanishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Eu/BasqueAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fa/PersianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fi/FinnishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fr/FrenchAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ga/IrishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Gl/GalicianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hi/HindiAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hu/HungarianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hy/ArmenianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Id/IndonesianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/It/ItalianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Lv/LatvianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/PatternAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/No/NorwegianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Pt/PortugueseAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ro/RomanianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Ru/RussianAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Snowball/SnowballAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Sv/SwedishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Th/ThaiAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Tr/TurkishAnalyzer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/CharArrayMap.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/CharArraySet.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/StopwordAnalyzerBase.cs
  src/Lucene.Net.Analysis.Kuromoji/JapaneseAnalyzer.cs
  src/Lucene.Net.Analysis.Morfologik/Uk/UkrainianMorfologikAnalyzer.cs
  src/Lucene.Net.Analysis.SmartCn/SmartChineseAnalyzer.cs
  src/Lucene.Net.Analysis.Stempel/Pl/PolishAnalyzer.cs
  src/Lucene.Net.Expressions/JS/JavascriptCompiler.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArrayMap.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestCharArraySet.cs
  src/Lucene.Net.Tests.Analysis.Kuromoji/TestJapaneseAnalyzer.cs
  src/Lucene.Net.Tests.Analysis.SmartCn/TestSmartChineseAnalyzer.cs
  src/Lucene.Net/Codecs/PostingsFormat.cs
  src/Lucene.Net/Index/Fields.cs
  src/Lucene.Net/Index/MultiTermsEnum.cs
  src/Lucene.Net/Index/ReaderSlice.cs
  src/Lucene.Net/Index/Terms.cs
  src/Lucene.Net/Util/Bits.cs
  src/Lucene.Net/Util/BytesRef.cs
  src/Lucene.Net/Util/CharsRef.cs
  src/Lucene.Net/Util/IntsRef.cs
  src/Lucene.Net/Util/LongsRef.cs
  src/dotnet/tools/lucene-cli/CommandLine/CommandLineApplication.cs
Labels: hacktoberfest-accepted

#711 Lucene.Net.Search.Similarities: Statically imported SimilarityBase, where approrpriate
  src/Lucene.Net/Search/Similarities/BasicModelBE.cs
  src/Lucene.Net/Search/Similarities/BasicModelD.cs
  src/Lucene.Net/Search/Similarities/BasicModelG.cs
  src/Lucene.Net/Search/Similarities/BasicModelIF.cs
  src/Lucene.Net/Search/Similarities/BasicModelIn.cs
  src/Lucene.Net/Search/Similarities/BasicModelIne.cs
  src/Lucene.Net/Search/Similarities/BasicModelP.cs
  src/Lucene.Net/Search/Similarities/NormalizationH2.cs
Labels: hacktoberfest-accepted

#712 Lucene.Net.Analysis.Kuromoji.Util.CSVUtil: Fixed QuoteEscape method
  src/Lucene.Net.Analysis.Kuromoji/Util/CSVUtil.cs
  src/Lucene.Net.Tests.Analysis.Kuromoji/Util/TestCSVUtil.cs
Labels: hacktoberfest-accepted

#714 Review for CA1822: Mark members as static (2)
  src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/De/GermanLightStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Fi/FinnishLightStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hu/HungarianLightStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/In/IndicNormalizer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/AbstractAnalysisFactory.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs
  src/Lucene.Net.Misc/Index/Sorter/BlockJoinComparatorSource.cs
  src/Lucene.Net.TestFramework/Support/JavaCompatibility/LuceneTestCase.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneRandomSeedInitializer.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneSetUpFixtureBuilder.cs
  src/Lucene.Net/Index/DocumentsWriterFlushQueue.cs
Labels: hacktoberfest-accepted

#718 Review for CA1822: Mark members as static (3)
  src/Lucene.Net.Analysis.Common/Analysis/Br/BrazilianStemmer.cs
Labels: hacktoberfest-accepted

#726 Disabled slow tests for PR test runs
  .github/workflows/Generate-TestWorkflows.ps1
  .github/workflows/Lucene-Net-Tests-AllProjects.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Common.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Kuromoji.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Morfologik.yml
  .github/workflows/Lucene-Net-Tests-Analysis-OpenNLP.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Phonetic.yml
  .github/workflows/Lucene-Net-Tests-Analysis-SmartCn.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Stempel.yml
  .github/workflows/Lucene-Net-Tests-Benchmark.yml
  .github/workflows/Lucene-Net-Tests-Classification.yml
  .github/workflows/Lucene-Net-Tests-Cli.yml
  .github/workflows/Lucene-Net-Tests-CodeAnalysis.yml
  .github/workflows/Lucene-Net-Tests-Codecs.yml
  .github/workflows/Lucene-Net-Tests-Demo.yml
  .github/workflows/Lucene-Net-Tests-Expressions.yml
  .github/workflows/Lucene-Net-Tests-Facet.yml
  .github/workflows/Lucene-Net-Tests-Grouping.yml
  .github/workflows/Lucene-Net-Tests-Highlighter.yml
  .github/workflows/Lucene-Net-Tests-ICU.yml
  .github/workflows/Lucene-Net-Tests-Join.yml
  .github/workflows/Lucene-Net-Tests-Memory.yml
  .github/workflows/Lucene-Net-Tests-Misc.yml
  .github/workflows/Lucene-Net-Tests-Queries.yml
  .github/workflows/Lucene-Net-Tests-QueryParser.yml
  .github/workflows/Lucene-Net-Tests-Replicator.yml
  .github/workflows/Lucene-Net-Tests-Sandbox.yml
  .github/workflows/Lucene-Net-Tests-Spatial.yml
  .github/workflows/Lucene-Net-Tests-Suggest.yml
  .github/workflows/Lucene-Net-Tests-TestFramework-DependencyInjection.yml
  .github/workflows/Lucene-Net-Tests-TestFramework.yml
  .github/workflows/Lucene-Net-Tests-_A-D.yml
  .github/workflows/Lucene-Net-Tests-_E-I.yml
  .github/workflows/Lucene-Net-Tests-_I-J.yml
  .github/workflows/Lucene-Net-Tests-_J-S.yml
  .github/workflows/Lucene-Net-Tests-_T-Z.yml
Labels: hacktoberfest-accepted

#727 Disabled Json Source Generator.
  Directory.Build.targets
Labels: hacktoberfest-accepted

#728 Updated Azure DevOps Mac OS used for Net3.1 Testing
  azure-pipelines.yml
Labels: hacktoberfest-accepted

#730 Sonar changes required for #671
  src/Lucene.Net.Analysis.Common/Analysis/Compound/Hyphenation/HyphenationTree.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs
  src/Lucene.Net.Analysis.Common/Analysis/Sinks/TeeSinkTokenFilter.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/BasqueStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/CatalanStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/EnglishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/FrenchStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/ItalianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/KpStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PorterStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PortugueseStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/RomanianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/RussianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/SpanishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/TurkishStemmer.cs
  src/Lucene.Net.Codecs/Memory/DirectPostingsFormat.cs
  src/Lucene.Net.Codecs/Memory/FSTOrdTermsReader.cs
  src/Lucene.Net.Codecs/Memory/FSTTermsReader.cs
  src/Lucene.Net.Codecs/Pulsing/PulsingPostingsReader.cs
  src/Lucene.Net.Expressions/JS/JavascriptLexer.cs
  src/Lucene.Net.Expressions/JS/JavascriptParser.cs
  src/Lucene.Net.Facet/DrillSidewaysScorer.cs
  src/Lucene.Net.Facet/Taxonomy/WriterCache/CollisionMap.cs
  src/Lucene.Net.Join/Support/ToChildBlockJoinQuery.cs
  src/Lucene.Net.Join/ToChildBlockJoinQuery.cs
  src/Lucene.Net.QueryParser/Classic/QueryParser.cs
  src/Lucene.Net.QueryParser/Classic/QueryParserTokenManager.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs
  src/Lucene.Net.QueryParser/Surround/Parser/QueryParser.cs
  src/Lucene.Net.QueryParser/Surround/Parser/QueryParserTokenManager.cs
  src/Lucene.Net.Spatial/Prefix/AbstractVisitingPrefixTreeFilter.cs
  src/Lucene.Net.Suggest/Spell/SpellChecker.cs
  src/Lucene.Net.Suggest/Suggest/Analyzing/FreeTextSuggester.cs
  src/Lucene.Net/Codecs/BlockTreeTermsReader.cs
  src/Lucene.Net/Codecs/Compressing/LZ4.cs
  src/Lucene.Net/Search/FieldCacheRangeFilter.cs
  src/Lucene.Net/Search/SloppyPhraseScorer.cs
  src/Lucene.Net/Store/CompoundFileWriter.cs
  src/Lucene.Net/Util/WAH8DocIdSet.cs
Labels: hacktoberfest-accepted

#731 Added nameof for the sonar suggestions.
  src/Lucene.Net.Analysis.Common/Analysis/Synonym/SlowSynonymFilter.cs
Labels: hacktoberfest-accepted
