Repository apache/lucenenet, pull requests merged in 2024-11, with the labels that each got.

#1012 Moved .msbuildproj files into new proj/ folder
  Lucene.Net.sln
  proj/build.msbuildproj
  proj/github.msbuildproj
  proj/websites.msbuildproj
  websites/websites.msbuildproj
Labels: notes:ignore

#1015 Added "Improvements" Category for Release Notes
  .github/release.yml
  websites/site/contributing/make-release.md
Labels: notes:improvement

#781 Respect ignoreCase flag in CommonGramsFilterFactory
  src/Lucene.Net.Analysis.Common/Analysis/CommonGrams/CommonGramsFilterFactory.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Commongrams/TestCommonGramsFilterFactory.cs
Labels: notes:bug-fix

#1018 Test review A-D, #259
  src/Lucene.Net.Tests/Analysis/TestCachingTokenFilter.cs
  src/Lucene.Net.Tests/Analysis/TestCharFilter.cs
  src/Lucene.Net.Tests/Analysis/TestGraphTokenizers.cs
  src/Lucene.Net.Tests/Analysis/TestLookaheadTokenFilter.cs
  src/Lucene.Net.Tests/Analysis/TestMockAnalyzer.cs
  src/Lucene.Net.Tests/Analysis/TestMockCharFilter.cs
  src/Lucene.Net.Tests/Analysis/TestNumericTokenStream.cs
  src/Lucene.Net.Tests/Analysis/TestPosition.cs
  src/Lucene.Net.Tests/Analysis/TestReusableStringReader.cs
  src/Lucene.Net.Tests/Analysis/TestToken.cs
  src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs
  src/Lucene.Net.Tests/Analysis/TokenAttributes/TestSimpleAttributeImpl.cs
  src/Lucene.Net.Tests/Codecs/Compressing/AbstractTestCompressionMode.cs
  src/Lucene.Net.Tests/Codecs/Compressing/TestCompressingStoredFieldsFormat.cs
  src/Lucene.Net.Tests/Codecs/Compressing/TestCompressingTermVectorsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene3x/TestLucene3xPostingsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene3x/TestLucene3xTermVectorsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene3x/TestSurrogates.cs
  src/Lucene.Net.Tests/Codecs/Lucene3x/TestTermInfosReaderIndex.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestBitVector.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestLucene40DocValuesFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestLucene40PostingsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestLucene40PostingsReader.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestLucene40StoredFieldsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestLucene40TermVectorsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene40/TestReuseDocsEnum.cs
  src/Lucene.Net.Tests/Codecs/Lucene41/TestBlockPostingsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene41/TestBlockPostingsFormat2.cs
  src/Lucene.Net.Tests/Codecs/Lucene41/TestBlockPostingsFormat3.cs
  src/Lucene.Net.Tests/Codecs/Lucene41/TestForUtil.cs
  src/Lucene.Net.Tests/Codecs/Lucene41/TestLucene41StoredFieldsFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene42/TestLucene42DocValuesFormat.cs
  src/Lucene.Net.Tests/Codecs/Lucene45/TestLucene45DocValuesFormat.cs
  src/Lucene.Net.Tests/Codecs/PerField/TestPerFieldDocValuesFormat.cs
  src/Lucene.Net.Tests/Codecs/PerField/TestPerFieldPostingsFormat.cs
  src/Lucene.Net.Tests/Codecs/PerField/TestPerFieldPostingsFormat2.cs
  src/Lucene.Net.Tests/Document/TestBinaryDocument.cs
  src/Lucene.Net.Tests/Document/TestDateTools.cs
  src/Lucene.Net.Tests/Document/TestDocument.cs
  src/Lucene.Net.Tests/Document/TestField.cs
  src/Lucene.Net.Tests/TestDemo.cs
  src/Lucene.Net.Tests/TestExternalCodecs.cs
  src/Lucene.Net.Tests/TestMergeSchedulerExternal.cs
  src/Lucene.Net.Tests/TestSearch.cs
  src/Lucene.Net.Tests/TestSearchForDuplicates.cs
  src/Lucene.Net.Tests/TestWorstCaseTestBehavior.cs
  src/Lucene.Net/Analysis/ReusableStringReader.cs
  src/Lucene.Net/Support/StandardCharsets.cs
Labels: notes:improvement

#1030 BREAKING: Make ReusableStringReader internal
  src/Lucene.Net/Analysis/ReusableStringReader.cs
Labels: notes:breaking-change

#1032 Add comments to empty blocks to address Sonar csharpsquid:S108, #672
  src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/LimitTokenCountFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/LimitTokenPositionFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Miscellaneous/TrimFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Sinks/TeeSinkTokenFilter.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/BasqueStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/CatalanStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/DutchStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/EnglishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/FrenchStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/German2Stemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/GermanStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/ItalianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/KpStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PorterStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PortugueseStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/RomanianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/SpanishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/TurkishStemmer.cs
  src/Lucene.Net.Analysis.Kuromoji/Util/ToStringUtil.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/PhoneticEngine.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/Rule.cs
  src/Lucene.Net.Analysis.Phonetic/PhoneticFilter.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/BigramDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/WordDictionary.cs
  src/Lucene.Net.Analysis.Stempel/Egothor.Stemmer/MultiTrie2.cs
  src/Lucene.Net.Benchmark/ByTask/Tasks/AnalyzerFactoryTask.cs
  src/Lucene.Net.Benchmark/ByTask/Utils/Algorithm.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/Parser.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/XMLWriter.cs
  src/Lucene.Net.Codecs/SimpleText/SimpleTextStoredFieldsWriter.cs
  src/Lucene.Net.Codecs/SimpleText/SimpleTextTermVectorsWriter.cs
  src/Lucene.Net.Highlighter/Highlight/Highlighter.cs
  src/Lucene.Net.Highlighter/VectorHighlight/BaseFragmentsBuilder.cs
  src/Lucene.Net.QueryParser/Classic/QueryParser.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParser.cs
  src/Lucene.Net.QueryParser/Flexible/Standard/Parser/StandardSyntaxParserTokenManager.cs
  src/Lucene.Net.QueryParser/Surround/Parser/QueryParser.cs
  src/Lucene.Net.Spatial/Prefix/AbstractVisitingPrefixTreeFilter.cs
  src/Lucene.Net.Suggest/Spell/SpellChecker.cs
  src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletionBuilder.cs
  src/Lucene.Net/Codecs/Lucene3x/Lucene3xTermVectorsReader.cs
  src/Lucene.Net/Codecs/Lucene3x/TermInfosReader.cs
  src/Lucene.Net/Codecs/Lucene40/Lucene40StoredFieldsReader.cs
  src/Lucene.Net/Codecs/Lucene40/Lucene40StoredFieldsWriter.cs
  src/Lucene.Net/Codecs/Lucene40/Lucene40TermVectorsWriter.cs
  src/Lucene.Net/Index/CheckIndex.cs
  src/Lucene.Net/Index/IndexWriter.cs
  src/Lucene.Net/Index/TwoStoredFieldsConsumers.cs
  src/Lucene.Net/Store/Directory.cs
  src/Lucene.Net/Store/LockStressTest.cs
  src/Lucene.Net/Store/NativeFSLockFactory.cs
  src/Lucene.Net/Store/RAMOutputStream.cs
  src/Lucene.Net/Util/Fst/FST.cs
  src/Lucene.Net/Util/VirtualMethod.cs
Labels: notes:ignore

#1033 Fix incorrect usage of argument exceptions for Sonar csharpsquid:S3928, #682
  src/Lucene.Net.Analysis.Common/Analysis/Shingle/ShingleFilterFactory.cs
  src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Synonym/SynonymMap.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/CharacterUtils.cs
  src/Lucene.Net.Analysis.Kuromoji/JapaneseKatakanaStemFilterFactory.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/PhoneticEngine.cs
  src/Lucene.Net.Benchmark/ByTask/Benchmark.cs
  src/Lucene.Net.Benchmark/Quality/Trec/QueryDriver.cs
  src/Lucene.Net.Benchmark/Quality/Utils/QualityQueriesFinder.cs
  src/Lucene.Net.Benchmark/Utils/ExtractWikipedia.cs
  src/Lucene.Net.Facet/Taxonomy/PrintTaxonomyStats.cs
  src/Lucene.Net.Highlighter/VectorHighlight/BaseFragListBuilder.cs
  src/Lucene.Net.Misc/Index/IndexSplitter.cs
  src/Lucene.Net.Misc/Index/MultiPassIndexSplitter.cs
  src/Lucene.Net.Misc/Misc/GetTermInfo.cs
  src/Lucene.Net.Misc/Misc/HighFreqTerms.cs
  src/Lucene.Net.Misc/Misc/IndexMergeTool.cs
  src/Lucene.Net.Queries/TermFilter.cs
  src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletionBuilder.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Synonym/TestSynonymMapFilter.cs
  src/Lucene.Net.Tests.Queries/TermFilterTest.cs
  src/Lucene.Net/Index/IndexUpgrader.cs
  src/Lucene.Net/Index/IndexWriterConfig.cs
  src/Lucene.Net/Search/MinShouldMatchSumScorer.cs
  src/Lucene.Net/Store/CompoundFileWriter.cs
  src/Lucene.Net/Store/LockStressTest.cs
  src/Lucene.Net/Store/LockVerifyServer.cs
  src/Lucene.Net/Util/Automaton/BasicAutomata.cs
  src/Lucene.Net/Util/UnicodeUtil.cs
Labels: notes:improvement

#1035 Replace lucene.testSettings.config references with lucene.testsettings.json
  Lucene.Net.sln.DotSettings
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterOnJRECrash.cs
Labels: notes:website-or-documentation

#1036 Fixed encoding provider loading on .NET Framework (for .NET Standard 2.0 target)
  src/Lucene.Net.Analysis.Kuromoji/JapaneseTokenizerFactory.cs
  src/Lucene.Net.Analysis.Kuromoji/Support/Util/EncodingProviderInitializer.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsWriter.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/DictionaryBuilder.cs
  src/Lucene.Net.Analysis.SmartCn/AnalyzerProfile.cs
  src/Lucene.Net.Analysis.SmartCn/Support/Util/EncodingProviderInitializer.cs
  src/Lucene.Net.Tests.Analysis.Common/Startup.cs
Labels: notes:bug-fix

#1028 Implement ISpanAppendable in CharBlockArray and CharTermAttributeImpl
  src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs
  src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCharBlockArray.cs
  src/Lucene.Net.Tests/Analysis/TokenAttributes/TestCharTermAttributeImpl.cs
  src/Lucene.Net/Analysis/TokenAttributes/CharTermAttribute.cs
  src/Lucene.Net/Analysis/TokenAttributes/CharTermAttributeImpl.cs
Labels: notes:improvement

#1042 Fix csharpsquid:S1117 SonarCloud warnings about shadowing fields with variable names
  src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/Nl/DutchAnalyzer.cs
  src/Lucene.Net.Analysis.ICU/Analysis/Icu/Segmentation/ScriptIterator.cs
  src/Lucene.Net.Analysis.Kuromoji/JapaneseAnalyzer.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/Lang.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/Languages.cs
  src/Lucene.Net.Benchmark/ByTask/Feeds/TrecDocParser.cs
  src/Lucene.Net.Benchmark/Support/TagSoup/ElementType.cs
  src/Lucene.Net.Misc/Document/LazyDocument.cs
  src/Lucene.Net.QueryParser/ComplexPhrase/ComplexPhraseQueryParser.cs
  src/Lucene.Net/Codecs/Lucene45/Lucene45DocValuesConsumer.cs
  src/Lucene.Net/Index/FieldInfos.cs
  src/Lucene.Net/Index/SortedSetDocValuesWriter.cs
  src/Lucene.Net/Support/CRC32.cs
  src/Lucene.Net/Util/SPIClassIterator.cs
Labels: notes:bug-fix

#1045 Enable TestICUFoldingFilterFactory.Test
  src/Lucene.Net.Tests.Analysis.ICU/Analysis/Icu/TestICUFoldingFilterFactory.cs
Labels: notes:ignore

#1047 Use upload-artifacts@4 GitHub action task, #1046
  .github/workflows/Generate-TestWorkflows.ps1
  .github/workflows/Lucene-Net-Tests-AllProjects.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Common.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Kuromoji.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Morfologik.yml
  .github/workflows/Lucene-Net-Tests-Analysis-OpenNLP.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Phonetic.yml
  .github/workflows/Lucene-Net-Tests-Analysis-SmartCn.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Stempel.yml
  .github/workflows/Lucene-Net-Tests-Benchmark.yml
  .github/workflows/Lucene-Net-Tests-Classification.yml
  .github/workflows/Lucene-Net-Tests-Cli.yml
  .github/workflows/Lucene-Net-Tests-CodeAnalysis.yml
  .github/workflows/Lucene-Net-Tests-Codecs.yml
  .github/workflows/Lucene-Net-Tests-Demo.yml
  .github/workflows/Lucene-Net-Tests-Expressions.yml
  .github/workflows/Lucene-Net-Tests-Facet.yml
  .github/workflows/Lucene-Net-Tests-Grouping.yml
  .github/workflows/Lucene-Net-Tests-Highlighter.yml
  .github/workflows/Lucene-Net-Tests-ICU.yml
  .github/workflows/Lucene-Net-Tests-Join.yml
  .github/workflows/Lucene-Net-Tests-Memory.yml
  .github/workflows/Lucene-Net-Tests-Misc.yml
  .github/workflows/Lucene-Net-Tests-Queries.yml
  .github/workflows/Lucene-Net-Tests-QueryParser.yml
  .github/workflows/Lucene-Net-Tests-Replicator.yml
  .github/workflows/Lucene-Net-Tests-Sandbox.yml
  .github/workflows/Lucene-Net-Tests-Spatial.yml
  .github/workflows/Lucene-Net-Tests-Suggest.yml
  .github/workflows/Lucene-Net-Tests-TestFramework-DependencyInjection.yml
  .github/workflows/Lucene-Net-Tests-TestFramework.yml
  .github/workflows/Lucene-Net-Tests-_A-D.yml
  .github/workflows/Lucene-Net-Tests-_E-I.yml
  .github/workflows/Lucene-Net-Tests-_I-J.yml
  .github/workflows/Lucene-Net-Tests-_J-S.yml
  .github/workflows/Lucene-Net-Tests-_T-Z.yml
  .github/workflows/Lucene-Net-Website.yml
Labels: notes:ignore

#1048 Expressions.JS: Bitwise left shift bugfixes, #1034
  src/Lucene.Net.Expressions/JS/JavascriptCompiler.cs
Labels: notes:bug-fix
