Repository apache/lucenenet, pull requests merged in 2025-10, with the labels that each got.

#1144 Optimize StemmerUtil for `ReadOnlySpan<char>`/`Span<char>`, #1140
  src/Lucene.Net.Analysis.Common/Analysis/Util/StemmerUtil.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestStemmerUtil.cs
Labels: notes:breaking-change

#1203 Remove and gitignore the `.idea` folder
  .gitignore
  .idea/.idea.Lucene.Net/.idea/.gitignore
  .idea/.idea.Lucene.Net/.idea/.name
  .idea/.idea.Lucene.Net/.idea/encodings.xml
  .idea/.idea.Lucene.Net/.idea/indexLayout.xml
  .idea/.idea.Lucene.Net/.idea/vcs.xml
Labels: notes:ignore

#1202 Upgrade dev analyzers to 1.0.0-alpha.18; make WindowsFsyncSupport internal, #1100
  .build/dependencies.props
  Directory.Build.targets
  TestTargetFramework.props
  src/Lucene.Net/Support/IO/WindowsFsyncSupport.cs
Labels: notes:bug-fix

#1154 feat: Optimize SmartCn Dictionaries and Add Dictionary Loading Tests
  src/Lucene.Net.Analysis.SmartCn/AnalyzerProfile.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/AbstractDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/BigramDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/WordDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/package.md
  src/Lucene.Net.Analysis.SmartCn/Lucene.Net.Analysis.SmartCn.csproj
  src/Lucene.Net.Analysis.SmartCn/Properties/AssemblyInfo.cs
  src/Lucene.Net.Analysis.SmartCn/overview.md
  src/Lucene.Net.Analysis.SmartCn/package.md
  src/Lucene.Net.Replicator/Http/package.md
  src/Lucene.Net.Replicator/overview.md
  src/Lucene.Net.Tests.Analysis.SmartCn/Hhmm/TestBuildDictionary.cs
  src/Lucene.Net.Tests.Analysis.SmartCn/Hhmm/custom-dictionary-input.zip
  src/Lucene.Net.Tests.Analysis.SmartCn/Lucene.Net.Tests.Analysis.SmartCn.csproj
Labels: notes:performance-improvement
