Repository apache/lucenenet, pull requests merged in 2025-01, with the labels that each got.

#1081 Simplify IndexReader constructor, #919
  src/Lucene.Net/Index/IndexReader.cs
Labels: notes:performance-improvement

#1083 SWEEP: Replace IndexOutOfRangeException with ArgumentOutOfRangeException except for indexer use, #1023
  src/Lucene.Net.Benchmark/Support/Sax/Ext/Attributes2.cs
  src/Lucene.Net.Benchmark/Support/Sax/Ext/Attributes2Impl.cs
  src/Lucene.Net.Benchmark/Support/Sax/Helpers/AttributesImpl.cs
  src/Lucene.Net.Codecs/SimpleText/SimpleTextDocValuesReader.cs
  src/Lucene.Net.Memory/MemoryIndexNormDocValues.cs
  src/Lucene.Net/Codecs/Lucene40/BitVector.cs
  src/Lucene.Net/Index/DocValues.cs
  src/Lucene.Net/Index/SegmentReader.cs
  src/Lucene.Net/Support/ExceptionHandling/ExceptionExtensions.cs
  src/Lucene.Net/Util/BytesRefArray.cs
  src/Lucene.Net/Util/UnicodeUtil.cs
Labels: notes:improvement

#1086 Use full test name in NUnit tests, #923
  .build/azure-templates/run-tests-on-os.yml
  .build/runbuild.ps1
  .github/workflows/Generate-TestWorkflows.ps1
  .github/workflows/Lucene-Net-Tests-AllProjects.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Common.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Kuromoji.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Morfologik.yml
  .github/workflows/Lucene-Net-Tests-Analysis-OpenNLP.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Phonetic.yml
  .github/workflows/Lucene-Net-Tests-Analysis-SmartCn.yml
  .github/workflows/Lucene-Net-Tests-Analysis-Stempel.yml
  .github/workflows/Lucene-Net-Tests-Benchmark.yml
  .github/workflows/Lucene-Net-Tests-Classification.yml
  .github/workflows/Lucene-Net-Tests-Cli.yml
  .github/workflows/Lucene-Net-Tests-CodeAnalysis.yml
  .github/workflows/Lucene-Net-Tests-Codecs.yml
  .github/workflows/Lucene-Net-Tests-Demo.yml
  .github/workflows/Lucene-Net-Tests-Expressions.yml
  .github/workflows/Lucene-Net-Tests-Facet.yml
  .github/workflows/Lucene-Net-Tests-Grouping.yml
  .github/workflows/Lucene-Net-Tests-Highlighter.yml
  .github/workflows/Lucene-Net-Tests-ICU.yml
  .github/workflows/Lucene-Net-Tests-Join.yml
  .github/workflows/Lucene-Net-Tests-Memory.yml
  .github/workflows/Lucene-Net-Tests-Misc.yml
  .github/workflows/Lucene-Net-Tests-Queries.yml
  .github/workflows/Lucene-Net-Tests-QueryParser.yml
  .github/workflows/Lucene-Net-Tests-Replicator.yml
  .github/workflows/Lucene-Net-Tests-Sandbox.yml
  .github/workflows/Lucene-Net-Tests-Spatial.yml
  .github/workflows/Lucene-Net-Tests-Suggest.yml
  .github/workflows/Lucene-Net-Tests-TestFramework-DependencyInjection.yml
  .github/workflows/Lucene-Net-Tests-TestFramework.yml
  .github/workflows/Lucene-Net-Tests-_A-D.yml
  .github/workflows/Lucene-Net-Tests-_E-I.yml
  .github/workflows/Lucene-Net-Tests-_I-J.yml
  .github/workflows/Lucene-Net-Tests-_J-S.yml
  .github/workflows/Lucene-Net-Tests-_T-Z.yml
  azure-pipelines.yml
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
Labels: notes:improvement

#1075 BREAKING: Use BOM-less UTF-8 encoding for writes, #1027
  src/Lucene.Net.Benchmark/ByTask/Tasks/WriteEnwikiLineDocTask.cs
  src/Lucene.Net.Benchmark/ByTask/Tasks/WriteLineDocTask.cs
  src/Lucene.Net.Benchmark/Quality/Trec/QueryDriver.cs
  src/Lucene.Net.Benchmark/Utils/ExtractReuters.cs
  src/Lucene.Net.Benchmark/Utils/ExtractWikipedia.cs
  src/Lucene.Net.TestFramework/Util/Fst/FSTTester.cs
  src/Lucene.Net.TestFramework/Util/TestUtil.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Hunspell/Test64kAffixes.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestFilesystemResourceLoader.cs
  src/Lucene.Net.Tests.Benchmark/ByTask/Feeds/DocMakerTest.cs
  src/Lucene.Net.Tests.Benchmark/ByTask/Feeds/LineDocSourceTest.cs
  src/Lucene.Net.Tests.Benchmark/ByTask/Utils/StreamUtilsTest.cs
  src/Lucene.Net.Tests.Demo/TestDemo.cs
  src/Lucene.Net.Tests.Facet/Taxonomy/TestTaxonomyFacetCounts.cs
  src/Lucene.Net.Tests/Index/TestCheckIndex.cs
  src/Lucene.Net.Tests/Index/TestDocInverterPerFieldErrorInfo.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterDelete.cs
  src/Lucene.Net.Tests/Index/TestPayloads.cs
  src/Lucene.Net.Tests/Search/Spans/TestBasics.cs
  src/Lucene.Net.Tests/Util/Fst/TestFSTs.cs
  src/Lucene.Net.Tests/Util/TestOfflineSorter.cs
  src/Lucene.Net/Codecs/Compressing/CompressingStoredFieldsReader.cs
  src/Lucene.Net/Codecs/Lucene3x/Lucene3xStoredFieldsReader.cs
  src/Lucene.Net/Codecs/Lucene40/Lucene40StoredFieldsReader.cs
  src/Lucene.Net/Index/Term.cs
  src/Lucene.Net/Support/StandardCharsets.cs
  src/Lucene.Net/Util/IOUtils.cs
  src/Lucene.Net/Util/OfflineSorter.cs
Labels: notes:breaking-change

#1078 Fix failing QueryParser Flexible tests due to zh-Hant-TW culture bug, #846
  src/Lucene.Net.Tests.QueryParser/Flexible/Standard/TestNumericQueryParser.cs
Labels: notes:bug-fix

#1091 Replace typeof(X).Name with nameof(X) #1077
  src/Lucene.Net.Analysis.Common/Analysis/NGram/EdgeNGramTokenizerFactory.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/CharacterDefinitionWriter.cs
  src/Lucene.Net.Benchmark/ByTask/Feeds/LongToEnglishQueryMaker.cs
  src/Lucene.Net.QueryParser/Flexible/Core/Builders/QueryTreeBuilder.cs
  src/Lucene.Net.Suggest/Suggest/Fst/FSTCompletionLookup.cs
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.TestFramework/Util/TestSecurityManager.cs
  src/Lucene.Net.Tests.QueryParser/Flexible/Messages/MessagesTestBundle.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterWithThreads.cs
  src/Lucene.Net.Tests/Search/TestBooleanScorer.cs
  src/Lucene.Net.Tests/Search/TestConstantScoreQuery.cs
  src/Lucene.Net/Codecs/Lucene3x/Lucene3xSegmentInfoFormat.cs
  src/Lucene.Net/Codecs/Lucene40/Lucene40FieldInfosReader.cs
  src/Lucene.Net/Codecs/PerField/PerFieldDocValuesFormat.cs
  src/Lucene.Net/Codecs/PerField/PerFieldPostingsFormat.cs
  src/Lucene.Net/Index/CheckIndex.cs
  src/Lucene.Net/Index/IndexUpgrader.cs
  src/Lucene.Net/Util/CommandLineUtil.cs
Labels: notes:improvement

#1092 Lucene.Net.TestFramework: Improved error handling and test reporting
  .build/azure-templates/publish-test-results.yml
  .build/azure-templates/run-tests-on-os.yml
  azure-pipelines.yml
  src/Lucene.Net.TestFramework/Search/RandomSimilarityProvider.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneTestCase.SetUpFixture.cs
  src/Lucene.Net.TestFramework/Support/Util/TestExtensions.cs
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.Tests.AllProjects/Support/ExceptionHandling/TestExceptionExtensions.cs
Labels: notes:improvement

#1084 Finish [SuppressTempFileChecks] attribute functionality, #898
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
Labels: notes:bug-fix

#1093 Add some Support unit tests, #920
  src/Lucene.Net.Tests/Support/Document/Extensions/TestIndexableFieldExtensions.cs
  src/Lucene.Net.Tests/Support/IO/TestByteArrayOutputStream.cs
  src/Lucene.Net.Tests/Support/TestAssemblyUtils.cs
  src/Lucene.Net.Tests/Support/TestDictionaryExtensions.cs
  src/Lucene.Net.Tests/Support/Util/TestCastTo.cs
  src/Lucene.Net.Tests/Support/Util/TestListExtensions.cs
Labels: notes:improvement

#1089 Use DecoderFallback.ExceptionFallback to match Java's CodingErrorAction.REPORT, #1076
  .gitignore
  Directory.Build.targets
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/ISO8859_14Decoder.cs
  src/Lucene.Net.Analysis.Common/Analysis/Synonym/FSTSynonymFilterFactory.cs
  src/Lucene.Net.Analysis.Common/Analysis/Util/AbstractAnalysisFactory.cs
  src/Lucene.Net.Analysis.Kuromoji/JapaneseTokenizerFactory.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/ConnectionCostsBuilder.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/TokenInfoDictionaryBuilder.cs
  src/Lucene.Net.Analysis.Kuromoji/Tools/UnknownDictionaryBuilder.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/AbstractDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/BigramDictionary.cs
  src/Lucene.Net.Analysis.SmartCn/Hhmm/WordDictionary.cs
  src/Lucene.Net.Benchmark/ByTask/Feeds/ContentItemsSource.cs
  src/Lucene.Net.Benchmark/ByTask/Tasks/CreateIndexTask.cs
  src/Lucene.Net.Benchmark/Quality/Trec/QueryDriver.cs
  src/Lucene.Net.TestFramework/Support/ExceptionHandling/ExceptionExtensions.cs
  src/Lucene.Net.TestFramework/Util/LineFileDocs.cs
  src/Lucene.Net.Tests.AllProjects/Support/ExceptionHandling/ExceptionScanningTestCase.cs
  src/Lucene.Net.Tests.AllProjects/Support/ExceptionHandling/TestExceptionExtensions.cs
  src/Lucene.Net.Tests.Benchmark/ByTask/Tasks/CreateIndexTaskTest.cs
  src/Lucene.Net.Tests.Demo/TestDemo.cs
  src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCharBlockArray.cs
  src/Lucene.Net.Tests.Facet/Taxonomy/WriterCache/TestCompactLabelToOrdinal.cs
  src/Lucene.Net.Tests/Index/TestTerm.cs
  src/Lucene.Net.Tests/Support/TestApiConsistency.cs
  src/Lucene.Net.Tests/Support/Text/TestEncodingExtensions.cs
  src/Lucene.Net/Index/Term.cs
  src/Lucene.Net/Support/Buffers/ArrayPoolExtensions.cs
  src/Lucene.Net/Support/ExceptionHandling/ExceptionExtensions.cs
  src/Lucene.Net/Support/Text/EncodingExtensions.cs
  src/Lucene.Net/Util/IOUtils.cs
Labels: notes:improvement

#1095 IDisposable Pattern Cleanup and fix TestDictionary.TestResourceCleanup, #265
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/Dictionary.cs
  src/Lucene.Net.TestFramework/Codecs/Lucene42/Lucene42DocValuesConsumer.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Hunspell/TestDictionary.cs
Labels: notes:bug-fix

#1099 Remove unnecessary NoInlining, #931
  src/Lucene.Net.Facet/DrillDownQuery.cs
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterExceptions.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterOnDiskFull.cs
  src/Lucene.Net.Tests/Index/TestIndexWriterWithThreads.cs
  src/Lucene.Net.Tests/Index/TestPersistentSnapshotDeletionPolicy.cs
  src/Lucene.Net/Codecs/LiveDocsFormat.cs
  src/Lucene.Net/Codecs/StoredFieldsWriter.cs
  src/Lucene.Net/Codecs/TermVectorsWriter.cs
  src/Lucene.Net/Index/BinaryDocValuesWriter.cs
  src/Lucene.Net/Index/DocConsumer.cs
  src/Lucene.Net/Index/DocFieldConsumer.cs
  src/Lucene.Net/Index/DocFieldConsumerPerField.cs
  src/Lucene.Net/Index/DocValuesFieldUpdates.cs
  src/Lucene.Net/Index/DocValuesProcessor.cs
  src/Lucene.Net/Index/DocValuesWriter.cs
  src/Lucene.Net/Index/FreqProxTermsWriter.cs
  src/Lucene.Net/Index/IMergeScheduler.cs
  src/Lucene.Net/Index/InvertedDocConsumer.cs
  src/Lucene.Net/Index/InvertedDocConsumerPerField.cs
  src/Lucene.Net/Index/InvertedDocEndConsumer.cs
  src/Lucene.Net/Index/InvertedDocEndConsumerPerField.cs
  src/Lucene.Net/Index/MergeScheduler.cs
  src/Lucene.Net/Index/NoMergeScheduler.cs
  src/Lucene.Net/Index/NormsConsumer.cs
  src/Lucene.Net/Index/NormsConsumerPerField.cs
  src/Lucene.Net/Index/NumericDocValuesWriter.cs
  src/Lucene.Net/Index/SegmentMerger.cs
  src/Lucene.Net/Index/SortedDocValuesWriter.cs
  src/Lucene.Net/Index/SortedSetDocValuesWriter.cs
  src/Lucene.Net/Index/StoredFieldsConsumer.cs
  src/Lucene.Net/Index/TermVectorsConsumer.cs
  src/Lucene.Net/Index/TermsHashConsumer.cs
  src/Lucene.Net/Store/IndexOutput.cs
  src/Lucene.Net/Util/Packed/AbstractBlockPackedWriter.cs
  src/Lucene.Net/Util/TimSorter.cs
Labels: notes:performance-improvement

#1096 Added DisposeAfterSuite/DisposeAfterTest feature to test framework
  src/Lucene.Net.TestFramework/Support/Util/DisposableResourceInfo.cs
  src/Lucene.Net.TestFramework/Support/Util/LifecycleScope.cs
  src/Lucene.Net.TestFramework/Support/Util/RandomizedContext.cs
  src/Lucene.Net.TestFramework/Support/Util/TestExtensions.cs
  src/Lucene.Net.TestFramework/Util/CloseableDirectory.cs
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.TestFramework/Util/TestRuleMarkFailure.cs
  src/Lucene.Net.Tests.Grouping/TestGroupingExtra.cs
  src/Lucene.Net.Tests.TestFramework/Support/TestApiConsistency.cs
  src/Lucene.Net.Tests/Util/Fst/TestFSTs.cs
Labels: notes:new-feature

#1104 Fix TestBufferedCharFilter.Test_Ready failing test, #1102
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Util/TestBufferedCharFilter.cs
Labels: notes:bug-fix

#1108 Lucene.Net.Replicator.LocalReplicator.ReplicationSession: Removed unnecessary array allocation
  src/Lucene.Net.Replicator/LocalReplicator.cs
Labels: notes:performance-improvement

#1107 Lucene.Net.Util.Events.TestPubSubEvent::CanAddSubscriptionWhileEventIsFiringNonGeneric(): Added [Ignore] attribute
  src/Lucene.Net.Tests/Support/Util/Events/TestPubSubEvent.cs
Labels: notes:ignore

#1109 Add unit tests for StreamExtensions, #1105
  src/Lucene.Net.Facet/Taxonomy/WriterCache/CharBlockArray.cs
  src/Lucene.Net.Tests/Support/IO/TestStreamExtensions.cs
Labels: notes:improvement

#1120 Add unit tests for ExceptionExtensions, #1112
  src/Lucene.Net.Tests/Util/TestExceptionExtensions.cs
Labels: notes:improvement

#1119 Add unit tests for LimitedConcurrencyLevelTaskScheduler, #1110
  Directory.Build.targets
  src/Lucene.Net.Tests/Support/Threading/JSR166TestCase.cs
  src/Lucene.Net.Tests/Support/Threading/TestLimitedConcurrencyLevelTaskScheduler.cs
  src/Lucene.Net/Support/Threading/LimitedConcurrencyLevelTaskScheduler.cs
Labels: notes:improvement

#1125 Added RepeatAttribute that is aware of RandomizedContext
  .build/azure-templates/publish-test-results-for-test-projects.yml
  .github/workflows/Lucene-Net-Tests-TestFramework-NUnitExtensions.yml
  LICENSE.txt
  Lucene.Net.sln
  src/Lucene.Net.TestFramework/Lucene.Net.TestFramework.csproj
  src/Lucene.Net.TestFramework/Support/Util/DefaultNamespaceTypeWrapper.cs
  src/Lucene.Net.TestFramework/Support/Util/DisposableResourceInfo.cs
  src/Lucene.Net.TestFramework/Support/Util/LifecycleScope.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneRandomSeedInitializer.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneTestCase.RepeatAttribute.cs
  src/Lucene.Net.TestFramework/Support/Util/LuceneTestCase.TestFixtureAttribute.cs
  src/Lucene.Net.TestFramework/Support/Util/NUnitTestFixtureBuilder.cs
  src/Lucene.Net.TestFramework/Support/Util/RandomizedContext.cs
  src/Lucene.Net.TestFramework/Support/Util/SeedUtils.cs
  src/Lucene.Net.TestFramework/Util/LuceneTestCase.cs
  src/Lucene.Net.Tests.TestFramework.NUnitExtensions/Attributes/RepeatAttributeTests.CustomMethodWrapper.cs
  src/Lucene.Net.Tests.TestFramework.NUnitExtensions/Attributes/RepeatAttributeTests.CustomTypeWrapper.cs
  src/Lucene.Net.Tests.TestFramework.NUnitExtensions/Attributes/RepeatAttributeTests.cs
  src/Lucene.Net.Tests.TestFramework.NUnitExtensions/Lucene.Net.Tests.TestFramework.NUnitExtensions.csproj
  src/dotnet/Lucene.Net.TestFramework.TestData.NUnit/Lucene.Net.TestFramework.TestData.NUnit.csproj
  src/dotnet/Lucene.Net.TestFramework.TestData.NUnit/RepeatingTests/RepeatedTestFixture.cs
  src/dotnet/Lucene.Net.TestFramework.TestData.NUnit/RepeatingTests/RepeatingTestsFixtureBase.cs
  src/dotnet/Lucene.Net.TestFramework.TestData.NUnit/TestUtilities/TestBuilder.cs
  src/dotnet/Lucene.Net.TestFramework.TestData.NUnit/TypeExtensions.cs
Labels: notes:improvement

#1122 Add Support unit tests for CollectionExtensions, #1115
  src/Lucene.Net.Tests/Support/TestCollectionExtensions.cs
Labels: notes:improvement
