Repository apache/lucenenet, pull requests merged in 2025-03, with the labels that each got.

#1136 Reduce Powershell build output noise
  .build/azure-templates/run-tests-on-os.yml
  .build/runbuild.ps1
Labels: notes:ignore

#1137 Fix random failing tests when near a DST boundary, #1133
  src/Lucene.Net.TestFramework/Index/AlcoholicMergePolicy.cs
Labels: notes:bug-fix

#1139 Remove unused private members, #669
  src/Lucene.Net.Analysis.Common/Analysis/CharFilter/HTMLStripCharFilter.cs
  src/Lucene.Net.Analysis.Common/Analysis/El/GreekStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/En/KStemmer.cs
  src/Lucene.Net.Analysis.Common/Analysis/Hunspell/HunspellStemFilterFactory.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/ArmenianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/BasqueStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/CatalanStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/DanishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/DutchStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/EnglishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/FinnishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/FrenchStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/German2Stemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/GermanStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/HungarianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/IrishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/ItalianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/KpStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/LovinsStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/NorwegianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PorterStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/PortugueseStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/RomanianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/RussianStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/SpanishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/SwedishStemmer.cs
  src/Lucene.Net.Analysis.Common/Tartarus/Snowball/Ext/TurkishStemmer.cs
  src/Lucene.Net.Analysis.Kuromoji/Support/Util/EncodingProviderInitializer.cs
  src/Lucene.Net.Analysis.Phonetic/Language/Bm/Rule.cs
  src/Lucene.Net.Analysis.SmartCn/Support/Util/EncodingProviderInitializer.cs
  src/Lucene.Net.Codecs/Memory/DirectPostingsFormat.cs
  src/Lucene.Net.Codecs/SimpleText/SimpleTextFieldsReader.cs
  src/Lucene.Net.Memory/MemoryIndex.MemoryIndexReader.cs
  src/Lucene.Net.Queries/Function/BoostedQuery.cs
  src/Lucene.Net.QueryParser/Classic/QueryParserTokenManager.cs
  src/Lucene.Net.QueryParser/Surround/Parser/QueryParserTokenManager.cs
  src/Lucene.Net/Index/Term.cs
  src/Lucene.Net/Support/Collections.cs
Labels: notes:ignore

#1149 BREAKING: Move CrankyTokenFilter to Lucene.Net.Analysis namespace (#1127)
  src/Lucene.Net.TestFramework/Analysis/CrankyTokenFilter.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestAllAnalyzersHaveFactories.cs
  src/Lucene.Net.Tests.Analysis.Common/Analysis/Core/TestRandomChains.cs
Labels: notes:breaking-change
